[package]
name = "const_init_macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "const_init_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.21.3"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"
